changelog:
  enabled: true

build:
  shopwareVersionConstraint: "~6.4.20"
  zip:
    composer:
      enabled: true
    assets:
      enabled: true
      enable_es_build_for_admin: false
      enable_es_build_for_storefront: false
    pack:
      excludes:
        paths:
          - .idea
          - var
          - .gitignore
