name: Build extension
on:
  workflow_dispatch:

jobs:
  build:
    - name: Shopware CLI Action
      uses: FriendsOfShopware/shopware-cli-action@v1.0.1
      with:
        extensionName: "EriveDelivery"
