name: Build extension
on:
  workflow_dispatch:

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/store-shopware-cli.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}